version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: jma
      WORDPRESS_DB_PASSWORD: Staub2002.
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: jma
      MYSQL_PASSWORD: Staub2002.
      MYSQL_ROOT_PASSWORD: Staub2002.
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
